export const MOCK = [
  {
    id: 1,
    title: "국가대표1",
    titleEng: "Take Off",
    genre: ["드라마", "액션", "코미디"],
    synopsis: {
      plotLang: "한국어",
      plotText:
        "자신도 대표하지 못하던 다섯 청춘들이 온 국민이 응원하는 스키점프 국가대표로 거듭나는 과정을 그린 유쾌한 스포츠 영화.",
    },
    openDate: "20090729",
    runningTimeMinute: "137",
    actors: ["하정우", "성동일", "김지석", "김동욱", "최재환"],
    directors: ["김용화"],
    producer: ["케이엠컬쳐㈜"],
    distributor: ["(주)쇼박스"],
    keywords: ["국가대표", "동계올림픽", "무주", "스키점프", "스포츠"],
    posterUrl: ["http://t1.daumcdn.net/cfile/171B311D4A4D462A37"],
    vodUrl: [
      [
        "http://file.koreafilm.or.kr/multi/00/04/63/MK046328.jpg",
        "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
      ],
      [
        "http://file.koreafilm.or.kr/multi/00/04/64/MK046422.jpg",
        "https://www.kmdb.or.kr/trailer/trailerPlayPop?pFileNm=MK046422_P02.mp4",
      ],
    ],
  },
  {
    id: 2,
    title: "국가대표2",
    titleEng: "Take Off",
    genre: ["드라마", "액션", "코미디"],
    synopsis: {
      plotLang: "한국어",
      plotText:
        "자신도 대표하지 못하던 다섯 청춘들이 온 국민이 응원하는 스키점프 국가대표로 거듭나는 과정을 그린 유쾌한 스포츠 영화.",
    },
    openDate: "20090729",
    runningTimeMinute: "137",
    actors: ["하정우", "성동일", "김지석", "김동욱", "최재환"],
    directors: ["김용화"],
    producer: ["케이엠컬쳐㈜"],
    distributor: ["(주)쇼박스"],
    keywords: ["국가대표", "동계올림픽", "무주", "스키점프", "스포츠"],
    posterUrl: ["http://t1.daumcdn.net/cfile/171B311D4A4D462A37"],
    vodUrl: [
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
    ],
  },
  {
    id: 3,
    title: "국가대표3",
    titleEng: "Take Off",
    genre: ["드라마", "액션", "코미디"],
    synopsis: {
      plotLang: "한국어",
      plotText:
        "자신도 대표하지 못하던 다섯 청춘들이 온 국민이 응원하는 스키점프 국가대표로 거듭나는 과정을 그린 유쾌한 스포츠 영화.",
    },
    openDate: "20090729",
    runningTimeMinute: "137",
    actors: ["하정우", "성동일", "김지석", "김동욱", "최재환"],
    directors: ["김용화"],
    producer: ["케이엠컬쳐㈜"],
    distributor: ["(주)쇼박스"],
    keywords: ["국가대표", "동계올림픽", "무주", "스키점프", "스포츠"],
    posterUrl: ["http://t1.daumcdn.net/cfile/171B311D4A4D462A37"],
    vodUrl: [
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
    ],
  },
  {
    id: 4,
    title: "국가대표4",
    titleEng: "Take Off",
    genre: ["드라마", "액션", "코미디"],
    synopsis: {
      plotLang: "한국어",
      plotText:
        "자신도 대표하지 못하던 다섯 청춘들이 온 국민이 응원하는 스키점프 국가대표로 거듭나는 과정을 그린 유쾌한 스포츠 영화.",
    },
    openDate: "20090729",
    runningTimeMinute: "137",
    actors: ["하정우", "성동일", "김지석", "김동욱", "최재환"],
    directors: ["김용화"],
    producer: ["케이엠컬쳐㈜"],
    distributor: ["(주)쇼박스"],
    keywords: ["국가대표", "동계올림픽", "무주", "스키점프", "스포츠"],
    posterUrl: ["http://t1.daumcdn.net/cfile/171B311D4A4D462A37"],
    vodUrl: [
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
    ],
  },
  {
    id: 5,
    title: "국가대표5",
    titleEng: "Take Off",
    genre: ["드라마", "액션", "코미디"],
    synopsis: {
      plotLang: "한국어",
      plotText:
        "자신도 대표하지 못하던 다섯 청춘들이 온 국민이 응원하는 스키점프 국가대표로 거듭나는 과정을 그린 유쾌한 스포츠 영화.",
    },
    openDate: "20090729",
    runningTimeMinute: "137",
    actors: ["하정우", "성동일", "김지석", "김동욱", "최재환"],
    directors: ["김용화"],
    producer: ["케이엠컬쳐㈜"],
    distributor: ["(주)쇼박스"],
    keywords: ["국가대표", "동계올림픽", "무주", "스키점프", "스포츠"],
    posterUrl: ["http://t1.daumcdn.net/cfile/171B311D4A4D462A37"],
    vodUrl: [
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
    ],
  },

  {
    id: 6,
    title: "국가대표6",
    titleEng: "Take Off",
    genre: ["드라마", "액션", "코미디"],
    synopsis: {
      plotLang: "한국어",
      plotText:
        "자신도 대표하지 못하던 다섯 청춘들이 온 국민이 응원하는 스키점프 국가대표로 거듭나는 과정을 그린 유쾌한 스포츠 영화.",
    },
    openDate: "20090729",
    runningTimeMinute: "137",
    actors: ["하정우", "성동일", "김지석", "김동욱", "최재환"],
    directors: ["김용화"],
    producer: ["케이엠컬쳐㈜"],
    distributor: ["(주)쇼박스"],
    keywords: ["국가대표", "동계올림픽", "무주", "스키점프", "스포츠"],
    posterUrl: ["http://t1.daumcdn.net/cfile/171B311D4A4D462A37"],
    vodUrl: [
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
    ],
  },
  {
    id: 7,
    title: "국가대표7",
    titleEng: "Take Off",
    genre: ["드라마", "액션", "코미디"],
    synopsis: {
      plotLang: "한국어",
      plotText:
        "자신도 대표하지 못하던 다섯 청춘들이 온 국민이 응원하는 스키점프 국가대표로 거듭나는 과정을 그린 유쾌한 스포츠 영화.",
    },
    openDate: "20090729",
    runningTimeMinute: "137",
    actors: ["하정우", "성동일", "김지석", "김동욱", "최재환"],
    directors: ["김용화"],
    producer: ["케이엠컬쳐㈜"],
    distributor: ["(주)쇼박스"],
    keywords: ["국가대표", "동계올림픽", "무주", "스키점프", "스포츠"],
    posterUrl: ["http://t1.daumcdn.net/cfile/171B311D4A4D462A37"],
    vodUrl: [
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
    ],
  },
  {
    id: 8,
    title: "국가대표8",
    titleEng: "Take Off",
    genre: ["드라마", "액션", "코미디"],
    synopsis: {
      plotLang: "한국어",
      plotText:
        "자신도 대표하지 못하던 다섯 청춘들이 온 국민이 응원하는 스키점프 국가대표로 거듭나는 과정을 그린 유쾌한 스포츠 영화.",
    },
    openDate: "20090729",
    runningTimeMinute: "137",
    actors: ["하정우", "성동일", "김지석", "김동욱", "최재환"],
    directors: ["김용화"],
    producer: ["케이엠컬쳐㈜"],
    distributor: ["(주)쇼박스"],
    keywords: ["국가대표", "동계올림픽", "무주", "스키점프", "스포츠"],
    posterUrl: ["http://t1.daumcdn.net/cfile/171B311D4A4D462A37"],
    vodUrl: [
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
    ],
  },
  {
    id: 9,
    title: "국가대표9",
    titleEng: "Take Off",
    genre: ["드라마", "액션", "코미디"],
    synopsis: {
      plotLang: "한국어",
      plotText:
        "자신도 대표하지 못하던 다섯 청춘들이 온 국민이 응원하는 스키점프 국가대표로 거듭나는 과정을 그린 유쾌한 스포츠 영화.",
    },
    openDate: "20090729",
    runningTimeMinute: "137",
    actors: ["하정우", "성동일", "김지석", "김동욱", "최재환"],
    directors: ["김용화"],
    producer: ["케이엠컬쳐㈜"],
    distributor: ["(주)쇼박스"],
    keywords: ["국가대표", "동계올림픽", "무주", "스키점프", "스포츠"],
    posterUrl: ["http://t1.daumcdn.net/cfile/171B311D4A4D462A37"],
    vodUrl: [
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
    ],
  },
  {
    id: 10,
    title: "국가대표10",
    titleEng: "Take Off",
    genre: ["드라마", "액션", "코미디"],
    synopsis: {
      plotLang: "한국어",
      plotText:
        "자신도 대표하지 못하던 다섯 청춘들이 온 국민이 응원하는 스키점프 국가대표로 거듭나는 과정을 그린 유쾌한 스포츠 영화.",
    },
    openDate: "20090729",
    runningTimeMinute: "137",
    actors: ["하정우", "성동일", "김지석", "김동욱", "최재환"],
    directors: ["김용화"],
    producer: ["케이엠컬쳐㈜"],
    distributor: ["(주)쇼박스"],
    keywords: ["국가대표", "동계올림픽", "무주", "스키점프", "스포츠"],
    posterUrl: ["http://t1.daumcdn.net/cfile/171B311D4A4D462A37"],
    vodUrl: [
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
    ],
  },
  {
    id: 11,
    title: "국가대표11",
    titleEng: "Take Off",
    genre: ["드라마", "액션", "코미디"],
    synopsis: {
      plotLang: "한국어",
      plotText:
        "자신도 대표하지 못하던 다섯 청춘들이 온 국민이 응원하는 스키점프 국가대표로 거듭나는 과정을 그린 유쾌한 스포츠 영화.",
    },
    openDate: "20090729",
    runningTimeMinute: "137",
    actors: ["하정우", "성동일", "김지석", "김동욱", "최재환"],
    directors: ["김용화"],
    producer: ["케이엠컬쳐㈜"],
    distributor: ["(주)쇼박스"],
    keywords: ["국가대표", "동계올림픽", "무주", "스키점프", "스포츠"],
    posterUrl: ["http://t1.daumcdn.net/cfile/171B311D4A4D462A37"],
    vodUrl: [
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
    ],
  },

  {
    id: 12,
    title: "국가대표12",
    titleEng: "Take Off",
    genre: ["드라마", "액션", "코미디"],
    synopsis: {
      plotLang: "한국어",
      plotText:
        "자신도 대표하지 못하던 다섯 청춘들이 온 국민이 응원하는 스키점프 국가대표로 거듭나는 과정을 그린 유쾌한 스포츠 영화.",
    },
    openDate: "20090729",
    runningTimeMinute: "137",
    actors: ["하정우", "성동일", "김지석", "김동욱", "최재환"],
    directors: ["김용화"],
    producer: ["케이엠컬쳐㈜"],
    distributor: ["(주)쇼박스"],
    keywords: ["국가대표", "동계올림픽", "무주", "스키점프", "스포츠"],
    posterUrl: ["http://t1.daumcdn.net/cfile/171B311D4A4D462A37"],
    vodUrl: [
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
    ],
  },

  {
    id: 13,
    title: "국가대표13",
    titleEng: "Take Off",
    genre: ["드라마", "액션", "코미디"],
    synopsis: {
      plotLang: "한국어",
      plotText:
        "자신도 대표하지 못하던 다섯 청춘들이 온 국민이 응원하는 스키점프 국가대표로 거듭나는 과정을 그린 유쾌한 스포츠 영화.",
    },
    openDate: "20090729",
    runningTimeMinute: "137",
    actors: ["하정우", "성동일", "김지석", "김동욱", "최재환"],
    directors: ["김용화"],
    producer: ["케이엠컬쳐㈜"],
    distributor: ["(주)쇼박스"],
    keywords: ["국가대표", "동계올림픽", "무주", "스키점프", "스포츠"],
    posterUrl: ["http://t1.daumcdn.net/cfile/171B311D4A4D462A37"],
    vodUrl: [
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
    ],
  },

  {
    id: 14,
    title: "국가대표14",
    titleEng: "Take Off",
    genre: ["드라마", "액션", "코미디"],
    synopsis: {
      plotLang: "한국어",
      plotText:
        "자신도 대표하지 못하던 다섯 청춘들이 온 국민이 응원하는 스키점프 국가대표로 거듭나는 과정을 그린 유쾌한 스포츠 영화.",
    },
    openDate: "20090729",
    runningTimeMinute: "137",
    actors: ["하정우", "성동일", "김지석", "김동욱", "최재환"],
    directors: ["김용화"],
    producer: ["케이엠컬쳐㈜"],
    distributor: ["(주)쇼박스"],
    keywords: ["국가대표", "동계올림픽", "무주", "스키점프", "스포츠"],
    posterUrl: ["http://t1.daumcdn.net/cfile/171B311D4A4D462A37"],
    vodUrl: [
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
    ],
  },

  {
    id: 15,
    title: "국가대표15",
    titleEng: "Take Off",
    genre: ["드라마", "액션", "코미디"],
    synopsis: {
      plotLang: "한국어",
      plotText:
        "자신도 대표하지 못하던 다섯 청춘들이 온 국민이 응원하는 스키점프 국가대표로 거듭나는 과정을 그린 유쾌한 스포츠 영화.",
    },
    openDate: "20090729",
    runningTimeMinute: "137",
    actors: ["하정우", "성동일", "김지석", "김동욱", "최재환"],
    directors: ["김용화"],
    producer: ["케이엠컬쳐㈜"],
    distributor: ["(주)쇼박스"],
    keywords: ["국가대표", "동계올림픽", "무주", "스키점프", "스포츠"],
    posterUrl: ["http://t1.daumcdn.net/cfile/171B311D4A4D462A37"],
    vodUrl: [
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
    ],
  },
];

export const MOCK2 = [
  {
    id: 1,
    title: "국가대표1",
    titleEng: "Take Off",
    genre: ["드라마", "액션", "코미디"],
    synopsis: {
      plotLang: "한국어",
      plotText:
        "자신도 대표하지 못하던 다섯 청춘들이 온 국민이 응원하는 스키점프 국가대표로 거듭나는 과정을 그린 유쾌한 스포츠 영화.",
    },
    openDate: "20090729",
    runningTimeMinute: "137",
    actors: ["하정우", "성동일", "김지석", "김동욱", "최재환"],
    directors: ["김용화"],
    producer: ["케이엠컬쳐㈜"],
    distributor: ["(주)쇼박스"],
    keywords: ["국가대표", "동계올림픽", "무주", "스키점프", "스포츠"],
    posterUrl: ["http://t1.daumcdn.net/cfile/171B311D4A4D462A37"],
    vodUrl: [
      [
        "http://file.koreafilm.or.kr/multi/00/04/63/MK046328.jpg",
        "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
      ],
      [
        "http://file.koreafilm.or.kr/multi/00/04/64/MK046422.jpg",
        "https://www.kmdb.or.kr/trailer/trailerPlayPop?pFileNm=MK046422_P02.mp4",
      ],
    ],
  },
  {
    id: 2,
    title: "국가대표2",
    titleEng: "Take Off",
    genre: ["드라마", "액션", "코미디"],
    synopsis: {
      plotLang: "한국어",
      plotText:
        "자신도 대표하지 못하던 다섯 청춘들이 온 국민이 응원하는 스키점프 국가대표로 거듭나는 과정을 그린 유쾌한 스포츠 영화.",
    },
    openDate: "20090729",
    runningTimeMinute: "137",
    actors: ["하정우", "성동일", "김지석", "김동욱", "최재환"],
    directors: ["김용화"],
    producer: ["케이엠컬쳐㈜"],
    distributor: ["(주)쇼박스"],
    keywords: ["국가대표", "동계올림픽", "무주", "스키점프", "스포츠"],
    posterUrl: ["http://t1.daumcdn.net/cfile/171B311D4A4D462A37"],
    vodUrl: [
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
    ],
  },
  {
    id: 3,
    title: "국가대표3",
    titleEng: "Take Off",
    genre: ["드라마", "액션", "코미디"],
    synopsis: {
      plotLang: "한국어",
      plotText:
        "자신도 대표하지 못하던 다섯 청춘들이 온 국민이 응원하는 스키점프 국가대표로 거듭나는 과정을 그린 유쾌한 스포츠 영화.",
    },
    openDate: "20090729",
    runningTimeMinute: "137",
    actors: ["하정우", "성동일", "김지석", "김동욱", "최재환"],
    directors: ["김용화"],
    producer: ["케이엠컬쳐㈜"],
    distributor: ["(주)쇼박스"],
    keywords: ["국가대표", "동계올림픽", "무주", "스키점프", "스포츠"],
    posterUrl: ["http://t1.daumcdn.net/cfile/171B311D4A4D462A37"],
    vodUrl: [
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
    ],
  },
  {
    id: 4,
    title: "국가대표4",
    titleEng: "Take Off",
    genre: ["드라마", "액션", "코미디"],
    synopsis: {
      plotLang: "한국어",
      plotText:
        "자신도 대표하지 못하던 다섯 청춘들이 온 국민이 응원하는 스키점프 국가대표로 거듭나는 과정을 그린 유쾌한 스포츠 영화.",
    },
    openDate: "20090729",
    runningTimeMinute: "137",
    actors: ["하정우", "성동일", "김지석", "김동욱", "최재환"],
    directors: ["김용화"],
    producer: ["케이엠컬쳐㈜"],
    distributor: ["(주)쇼박스"],
    keywords: ["국가대표", "동계올림픽", "무주", "스키점프", "스포츠"],
    posterUrl: ["http://t1.daumcdn.net/cfile/171B311D4A4D462A37"],
    vodUrl: [
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
      "https://www.kmdb.or.kr/trailer/play/MK006806_P03.mp4",
    ],
  },
];
